<!-- <li><a href="#">About CC</a></li> -->
<li><a href="/about/licenses/"><?php _e('The Licenses', 'cc5'); ?></a></li>
<li><a href="/about/newsletter"><?php _e('Newsletter', 'cc5'); ?></a></li>
<li><a href="/about/events"><?php _e('Events', 'cc5'); ?></a></li>
<li><a href="https://support.creativecommons.org/supporters"><?php _e('Supporters', 'cc5'); ?></a></li>
<li><a href="/about/opportunities"><?php _e('Jobs', 'cc5'); ?></a></li>
<li><a href="http://wiki.creativecommons.org/Developers"><?php _e('Developers', 'cc5'); ?></a></li>
<li><a href="http://wiki.creativecommons.org/Case_Studies"><?php _e('Case Studies', 'cc5'); ?></a></li>
<li><a href="/interviews"><?php _e('CC Talks With...', 'cc5'); ?></a></li>
<li><a href="http://learn.creativecommons.org/"><?php _e('Education', 'cc5'); ?></a></li>
<li><a href="http://sciencecommons.org/"><?php _e('Science', 'cc5'); ?></a></li>
<li><a href="/contact"><?php _e('Contact', 'cc5'); ?></a></li>
<!-- <li><a href="#">Documentation</a></li> -->
