= 1.6.2 =

+ fixed case sensatvity issues on some configs of php

= 1.6.1 =

+ created new version to overcome problem with corrupt project at wordpress.org

= 1.6.0 =


+ Improved form edit screen
+ Fixed problem with special characters in questions 
+ Fixed problem with table name length

= 1.5.1 =

+ update with all library function changes.
+ moved as much styling from page into css as possible
+ solved problem with fnmatch not being available in php for windows platforms will version 5.3
+ improved support of special characters
+ changed layout of edit screen to improved support for multiple value select and drop down boxes

= 1.5.0 =

Major new reboot and rewrite for WordPress 3.0