<?php echo $this->options['name']; ?> is an easy to use and easy to modify survey tool for WordPress. Written to be easy to use to none coders.

You can design many contact surveys with various type of data collection including checkboxes ,radio buttons, textboxes textareas and many more and allows you to choose which fields you want to be mandatory.
It also contains a simple CAPTCHA to help prevent SPAM or if you with you can use the more elaborate Recaptcha.

You able to access the survey data directly via its own MySQL table or download the data in CVS format to import into any spreadsheet package.
